<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
  <script type="text/javascript">
    /*
    The code of a promise executor and promise handlers has an
    "invisible try..catch" around it. If an exception happens, it
    gets caught and treated as a rejection.
    */
    let p = new Promise((resolve, reject)  => {
      try {
        throw (new Error("Que fallo!"));
      } catch (e) {
        reject( "tilin!");
      }
    }).catch( (e) => console.log("Everything worked! "+e));
    /* Chrome:
      Everything worked! tilin!
    */
  </script>
</body>
</html>
